chore(frontend): add runner of tests with jest

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,6 +1,10 @@
 echo 'Checking Lint for Frontend'
 npm run lint:frontend || (echo 'Lint on Frontend Failed' && exit 1)
 
+echo 'Running Frontend Tests'
+npm run test:frontend test || (echo 'Unit Tests on Frontend Failed' && exit 1)
+echo 'Frontend Tests Finished'
+
 echo 'Checking Lint for Mobile'
 npm run lint:mobile || (echo 'Lint on Mobile Failed' && exit 1)
 
@@ -12,7 +16,7 @@ echo 'Lint Finished'
 
 echo 'Running Backend Tests'
 echo 'Running Backend Unit Tests'
-npm run test || (echo 'Unit Tests on Backend Failed' && exit 1)
+npm run test:backend || (echo 'Unit Tests on Backend Failed' && exit 1)
 echo 'Running Backend E2E Tests'
-npm run test || (echo 'E2E Tests on Backend Failed' && exit 1)
+npm run test:backend || (echo 'E2E Tests on Backend Failed' && exit 1)
 echo 'Backend Tests Finished'
